Added some more explanations
hassanzhd/FAST-Resources pull request #17
Opened 2023-07-19 12:40 UTC by aikhan

2023-07-19 13:11 UTC, Rubix982 requested changes
Some grammatical/typing fixes suggested.

2023-07-19 13:11 UTC, Rubix982 commented on Operating Systems/concepts.txt
> +LOADER: Loaders brings the program into memory inorder for it to be executed. Modern systems dont bring in libraries into executable rather use DLLs that are loaded as needed. (Static Libraries are b
Typo! `noth` -> `both`.

2023-07-19 13:11 UTC, Rubix982 commented on Operating Systems/concepts.txt
> +LAYERED: Another approach is to create multiple small layers. In which each layer depends upon the services the layer below. No lower layer can use services of upper layer. This can be inefficient as
`but it does provides abstraction makes the code less cohesive.` -> `but it does provide abstraction whihc makes the code less cohesive`.

2023-07-19 13:11 UTC, Rubix982 commented
Hi Ali! Thanks for the PR! I've left some comments from my review. Feel free to ping when you're done.

2023-07-19 15:42 UTC, aikhan commented
Sorry for the typos, I've fixed them now.

Thanks

2023-07-20 03:51 UTC, Rubix982 commented
LGTM.

@HassanZhd.

2023-07-20 12:06 UTC, merged